spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:customer_management
    username: sa
    password: password

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        hbm2ddl:
          auto: update

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

  h2:
    console:
      enabled: true